import { Inter, Prompt } from "next/font/google";
import { NavbarSimple } from "./components/Navber";
import Footer from "./components/Footer";
import { LanguageProvider } from "./LanguageContext";
import "./globals.css";

// const inter = Inter({ subsets: ["latin"] });
const prompt = Prompt({
  weight: ['100', '200', '300', '400', '500', '600', '700', '800', '900'],
  subsets: ['latin'],
  variable: '--font-prompt',
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${prompt.variable} font-prompt`}>
        <LanguageProvider>
          <NavbarSimple />
          {children}
          <Footer />
        </LanguageProvider>
      </body>
    </html>
  );
}
